
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BORN CLOSETD CONTENT CTBD CTR GARBAGE HREF OPENTD SPACE STARTER TBD TR YESTERDAY\n    start : YESTERDAY skipGARBAGE STARTER skipTD rows\n    \n    skipTD : CTR skipTD\n           | \n    \n    rows : GETrows rows\n         | CTBD\n    \n    GETrows : TR HREF HREF CTR \n            | TR HREF CTR \n            | TR CTR\n    \n    getCONTENTS : OPENTD getCONTENTS\n                | OPENTD CONTENT getCONTENTS \n                |\n    \n    skipGARBAGE : TR skipGARBAGE \n            | CTR skipGARBAGE\n            | \n    '
    
_lr_action_items = {'YESTERDAY':([0,],[2,]),'$end':([1,11,13,16,],[0,-1,-5,-4,]),'TR':([2,4,5,6,9,10,12,15,18,20,21,],[4,4,4,-3,14,-3,14,-2,-8,-7,-6,]),'CTR':([2,4,5,6,10,14,17,19,],[5,5,5,10,10,18,20,21,]),'STARTER':([2,3,4,5,7,8,],[-14,6,-14,-14,-12,-13,]),'CTBD':([6,9,10,12,15,18,20,21,],[-3,13,-3,13,-2,-8,-7,-6,]),'HREF':([14,17,],[17,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'skipGARBAGE':([2,4,5,],[3,7,8,]),'skipTD':([6,10,],[9,15,]),'rows':([9,12,],[11,16,]),'GETrows':([9,12,],[12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> YESTERDAY skipGARBAGE STARTER skipTD rows','start',5,'p_start','url_fetcher.py',75),
  ('skipTD -> CTR skipTD','skipTD',2,'p_skipTD','url_fetcher.py',79),
  ('skipTD -> <empty>','skipTD',0,'p_skipTD','url_fetcher.py',80),
  ('rows -> GETrows rows','rows',2,'p_rows','url_fetcher.py',85),
  ('rows -> CTBD','rows',1,'p_rows','url_fetcher.py',86),
  ('GETrows -> TR HREF HREF CTR','GETrows',4,'p_GETrows','url_fetcher.py',91),
  ('GETrows -> TR HREF CTR','GETrows',3,'p_GETrows','url_fetcher.py',92),
  ('GETrows -> TR CTR','GETrows',2,'p_GETrows','url_fetcher.py',93),
  ('getCONTENTS -> OPENTD getCONTENTS','getCONTENTS',2,'p_getCONTENTS','url_fetcher.py',106),
  ('getCONTENTS -> OPENTD CONTENT getCONTENTS','getCONTENTS',3,'p_getCONTENTS','url_fetcher.py',107),
  ('getCONTENTS -> <empty>','getCONTENTS',0,'p_getCONTENTS','url_fetcher.py',108),
  ('skipGARBAGE -> TR skipGARBAGE','skipGARBAGE',2,'p_skipGARBAGE','url_fetcher.py',119),
  ('skipGARBAGE -> CTR skipGARBAGE','skipGARBAGE',2,'p_skipGARBAGE','url_fetcher.py',120),
  ('skipGARBAGE -> <empty>','skipGARBAGE',0,'p_skipGARBAGE','url_fetcher.py',121),
]
