
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEBRACKET CONTENT DATA GARBAGE OPENBRACKET SPACE STARTER\n    start : STARTER skipCONTENT DATA CONTENT\n    \n    skipCONTENT : CONTENT skipCONTENT\n                |  \n    '
    
_lr_action_items = {'STARTER':([0,],[2,]),'$end':([1,7,],[0,-1,]),'CONTENT':([2,4,5,],[4,4,7,]),'DATA':([2,3,4,6,],[-3,5,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'skipCONTENT':([2,4,],[3,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> STARTER skipCONTENT DATA CONTENT','start',4,'p_start','graph_data.py',53),
  ('skipCONTENT -> CONTENT skipCONTENT','skipCONTENT',2,'p_skipCONTENT','graph_data.py',63),
  ('skipCONTENT -> <empty>','skipCONTENT',0,'p_skipCONTENT','graph_data.py',64),
]
