
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEHREF CONTENT FIRST H3 OPENHREF SECOND SKIPTAGstart : content_sectioncontent_section : FIRST content_itemscontent_items : content_item content_items\n                     | content_itemcontent_item : contents\n                    | FIRST\n                    | link\n                    | heading\n    heading : H3 CONTENT\n    contents : CONTENTlink : OPENHREF CONTENT CLOSEHREF\n            | OPENHREF CONTENT CONTENT CONTENT CLOSEHREF\n            | OPENHREF CONTENT CONTENT CLOSEHREF\n            | OPENHREF CLOSEHREF'
    
_lr_action_items = {'FIRST':([0,3,4,6,7,8,9,10,15,16,18,20,21,],[3,4,-6,4,-5,-7,-8,-10,-14,-9,-11,-13,-12,]),'$end':([1,2,4,5,6,7,8,9,10,13,15,16,18,20,21,],[0,-1,-6,-2,-4,-5,-7,-8,-10,-3,-14,-9,-11,-13,-12,]),'CONTENT':([3,4,6,7,8,9,10,11,12,14,15,16,17,18,20,21,],[10,-6,10,-5,-7,-8,-10,14,16,17,-14,-9,19,-11,-13,-12,]),'OPENHREF':([3,4,6,7,8,9,10,15,16,18,20,21,],[11,-6,11,-5,-7,-8,-10,-14,-9,-11,-13,-12,]),'H3':([3,4,6,7,8,9,10,15,16,18,20,21,],[12,-6,12,-5,-7,-8,-10,-14,-9,-11,-13,-12,]),'CLOSEHREF':([11,14,17,19,],[15,18,20,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'content_section':([0,],[2,]),'content_items':([3,6,],[5,13,]),'content_item':([3,6,],[6,6,]),'contents':([3,6,],[7,7,]),'link':([3,6,],[8,8,]),'heading':([3,6,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> content_section','start',1,'p_start','responses.py',80),
  ('content_section -> FIRST content_items','content_section',2,'p_content_section','responses.py',83),
  ('content_items -> content_item content_items','content_items',2,'p_content_items','responses.py',87),
  ('content_items -> content_item','content_items',1,'p_content_items','responses.py',88),
  ('content_item -> contents','content_item',1,'p_content_item','responses.py',92),
  ('content_item -> FIRST','content_item',1,'p_content_item','responses.py',93),
  ('content_item -> link','content_item',1,'p_content_item','responses.py',94),
  ('content_item -> heading','content_item',1,'p_content_item','responses.py',95),
  ('heading -> H3 CONTENT','heading',2,'p_heading','responses.py',99),
  ('contents -> CONTENT','contents',1,'p_contents','responses.py',114),
  ('link -> OPENHREF CONTENT CLOSEHREF','link',3,'p_link','responses.py',125),
  ('link -> OPENHREF CONTENT CONTENT CONTENT CLOSEHREF','link',5,'p_link','responses.py',126),
  ('link -> OPENHREF CONTENT CONTENT CLOSEHREF','link',4,'p_link','responses.py',127),
  ('link -> OPENHREF CLOSEHREF','link',2,'p_link','responses.py',128),
]
