
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEHREF CONTENT FIRST OPENHREF SECOND SKIPTAGstart : content_sectioncontent_section : FIRST content_itemscontent_items : content_item content_items\n                     | content_itemcontent_item : contents\n                    | FIRST\n                    | linkcontents : CONTENTlink : OPENHREF CONTENT CLOSEHREF\n            | OPENHREF CONTENT CONTENT CONTENT CLOSEHREF\n            | OPENHREF CONTENT CONTENT CLOSEHREF\n            | OPENHREF CLOSEHREF'
    
_lr_action_items = {'FIRST':([0,3,4,6,7,8,9,13,15,17,18,],[3,4,-6,4,-5,-7,-8,-12,-9,-11,-10,]),'$end':([1,2,4,5,6,7,8,9,11,13,15,17,18,],[0,-1,-6,-2,-4,-5,-7,-8,-3,-12,-9,-11,-10,]),'CONTENT':([3,4,6,7,8,9,10,12,13,14,15,17,18,],[9,-6,9,-5,-7,-8,12,14,-12,16,-9,-11,-10,]),'OPENHREF':([3,4,6,7,8,9,13,15,17,18,],[10,-6,10,-5,-7,-8,-12,-9,-11,-10,]),'CLOSEHREF':([10,12,14,16,],[13,15,17,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'content_section':([0,],[2,]),'content_items':([3,6,],[5,11,]),'content_item':([3,6,],[6,6,]),'contents':([3,6,],[7,7,]),'link':([3,6,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> content_section','start',1,'p_start','responses.py',42),
  ('content_section -> FIRST content_items','content_section',2,'p_content_section','responses.py',45),
  ('content_items -> content_item content_items','content_items',2,'p_content_items','responses.py',48),
  ('content_items -> content_item','content_items',1,'p_content_items','responses.py',49),
  ('content_item -> contents','content_item',1,'p_content_item','responses.py',52),
  ('content_item -> FIRST','content_item',1,'p_content_item','responses.py',53),
  ('content_item -> link','content_item',1,'p_content_item','responses.py',54),
  ('contents -> CONTENT','contents',1,'p_contents','responses.py',57),
  ('link -> OPENHREF CONTENT CLOSEHREF','link',3,'p_link','responses.py',67),
  ('link -> OPENHREF CONTENT CONTENT CONTENT CLOSEHREF','link',5,'p_link','responses.py',68),
  ('link -> OPENHREF CONTENT CONTENT CLOSEHREF','link',4,'p_link','responses.py',69),
  ('link -> OPENHREF CLOSEHREF','link',2,'p_link','responses.py',70),
]
